// Breed suggestions from a bundled list (src/data/breeds.json, regenerated by
// scripts/build-breeds.mjs). Works offline; any text is still allowed.
import breeds from '../data/breeds.json';
import type { Species } from './types';

const LISTS: Record<Species, string[]> = { Dog: breeds.Dog, Cat: breeds.Cat, Rabbit: breeds.Rabbit, Other: [] };

/** Lower-case and strip accents, so "bichon frise" finds "Bichon Frisé". */
const fold = (s: string) => s.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase();

/**
 * Up to `limit` breeds matching what's typed: names where a word starts with
 * the text come first, then names containing it anywhere.
 */
export function suggestBreeds(species: Species, text: string, limit = 6): string[] {
  const typed = text.trim();
  const q = fold(typed);
  if (!q) return [];
  const list = LISTS[species];
  const wordStart: string[] = [];
  const contains: string[] = [];
  for (const name of list) {
    // Hide it once typed exactly; still offer it if only case/accents differ.
    if (name === typed) continue;
    const n = fold(name);
    if (n.startsWith(q) || n.includes(` ${q}`) || n.includes(`-${q}`)) wordStart.push(name);
    else if (n.includes(q)) contains.push(name);
  }
  return [...wordStart, ...contains].slice(0, limit);
}
