// Regenerates src/data/breeds.json from Wikidata (CC0, public domain):
//   node scripts/build-breeds.mjs
// Dogs: breeds with an FCI catalogue number or an American Kennel Club ID
// (i.e. internationally recognised), plus common UK crossbreeds that no
// kennel club lists. Cats and rabbits: every breed Wikidata knows.
// Breeds marked as dissolved/extinct are left out. Commit the output.
import { writeFileSync } from 'node:fs';

const ENDPOINT = 'https://query.wikidata.org/sparql';
const USER_AGENT = 'PawpersBreedList/1.0 (https://github.com/Tubz64/field-card)';

const QUERIES = {
  Dog: `SELECT DISTINCT ?label WHERE {
    ?i wdt:P31 wd:Q39367 .
    { ?i wdt:P528 ?fci } UNION { ?i wdt:P13890 ?akc }
    FILTER NOT EXISTS { ?i wdt:P576 ?dissolved }
    ?i rdfs:label ?label FILTER(lang(?label) = "en")
  }`,
  Cat: `SELECT DISTINCT ?label WHERE {
    ?i wdt:P31 wd:Q43577 .
    FILTER NOT EXISTS { ?i wdt:P576 ?dissolved }
    ?i rdfs:label ?label FILTER(lang(?label) = "en")
  }`,
  Rabbit: `SELECT DISTINCT ?label WHERE {
    ?i wdt:P31 wd:Q12045584 .
    FILTER NOT EXISTS { ?i wdt:P576 ?dissolved }
    ?i rdfs:label ?label FILTER(lang(?label) = "en")
  }`,
};

/** Popular in the UK but not recognised breeds, so missing from Wikidata's lists. */
const EXTRA = {
  Dog: [
    'Cockapoo', 'Cavapoo', 'Labradoodle', 'Goldendoodle', 'Cavachon', 'Maltipoo', 'Sprocker',
    'Springador', 'Jackapoo', 'Puggle', 'Jug', 'Chorkie', 'Pomchi', 'Shih-poo', 'Bichon Frise cross',
    'Lurcher', 'Crossbreed', 'Mixed breed',
  ],
  Cat: ['Domestic shorthair', 'Domestic longhair', 'Moggy (mixed breed)'],
  Rabbit: ['Mixed breed'],
};

async function labels(query) {
  const url = `${ENDPOINT}?query=${encodeURIComponent(query)}`;
  const res = await fetch(url, { headers: { Accept: 'application/sparql-results+json', 'User-Agent': USER_AGENT } });
  if (!res.ok) throw new Error(`Wikidata query failed: ${res.status}`);
  const json = await res.json();
  return json.results.bindings.map((b) => b.label.value);
}

// Wikidata capitalisation is inconsistent ("border collie" next to "Labrador
// Retriever"), so title-case every word except particles ("Chien de ...").
const PARTICLES = new Set(['de', 'du', 'des', 'la', 'le', 'of', 'the', 'and', 'di', 'da', 'van', 'von']);
const clean = (name) =>
  name
    .trim()
    .replace(/\s+/g, ' ')
    .split(' ')
    .map((word, i) =>
      i > 0 && PARTICLES.has(word.toLowerCase())
        ? word.toLowerCase()
        : word.replace(/(^|-)(\p{Ll})/gu, (_, sep, ch) => sep + ch.toUpperCase()),
    )
    .join(' ');
// Drop entries that are clearly not a breed name (Q-ids, bracketed notes).
const usable = (name) => name.length > 1 && !/^Q\d+$/.test(name) && !name.includes('(breed');

const out = {
  _source:
    'Wikidata (CC0 public domain), generated by scripts/build-breeds.mjs, plus common UK crossbreeds. Suggestions only; any text is allowed.',
};
for (const [species, query] of Object.entries(QUERIES)) {
  const names = new Map();
  for (const name of [...(await labels(query)), ...EXTRA[species]]) {
    const c = clean(name);
    if (usable(c) && !names.has(c.toLowerCase())) names.set(c.toLowerCase(), c);
  }
  out[species] = [...names.values()].sort((a, b) => a.localeCompare(b, 'en', { sensitivity: 'base' }));
  console.log(`${species}: ${out[species].length}`);
}
writeFileSync(new URL('../src/data/breeds.json', import.meta.url), JSON.stringify(out, null, 2) + '\n');
