// Writes .env.local with the IDs the app needs for an environment, looked up
// by name with your AWS CLI credentials:
//   npm run configure            # dev
//   npm run configure -- prod
// The values aren't secret (they ship inside every app build), but keeping
// them out of this public repo avoids advertising the dev sign-up endpoint.
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const env = process.argv[2] ?? 'dev';
const region = 'eu-west-2';
const prefix = `pawpers-${env}`;

const aws = (...args) =>
  execFileSync('aws', [...args, '--region', region, '--output', 'text'], { encoding: 'utf8' }).trim();

const poolId = aws('cognito-idp', 'list-user-pools', '--max-results', '60', '--query', `UserPools[?Name=='${prefix}'].Id`);
if (!poolId) throw new Error(`User pool ${prefix} not found`);
const clientId = aws(
  'cognito-idp', 'list-user-pool-clients', '--user-pool-id', poolId,
  '--query', `UserPoolClients[?ClientName=='${prefix}-app'].ClientId`,
);
const apiUrl = aws('apigatewayv2', 'get-apis', '--query', `Items[?Name=='${prefix}-api'].ApiEndpoint`);
if (!clientId || !apiUrl) throw new Error(`App client or API for ${prefix} not found`);

writeFileSync(
  '.env.local',
  [
    `# Generated by npm run configure (${env}); not committed.`,
    `EXPO_PUBLIC_ENV=${env}`,
    `EXPO_PUBLIC_AWS_REGION=${region}`,
    `EXPO_PUBLIC_USER_POOL_ID=${poolId}`,
    `EXPO_PUBLIC_USER_POOL_CLIENT_ID=${clientId}`,
    `EXPO_PUBLIC_API_URL=${apiUrl}`,
    '',
  ].join('\n'),
);
console.log(`Wrote .env.local for ${prefix} (${apiUrl}). Restart Expo to pick it up.`);
